
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    connection-timeout: 5000ms
    servlet:
      context-path: /
    port: 8080

spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/security-monitor-330281?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&&autoReconnect=true&failOverReadOnly=false
        username: root
        password: 123

spring:
  jmx:
    enabled: false